apiVersion: v1
kind: Service
metadata:
  name: {{ include "loom.fullname" . }}-api
  labels:
    {{- include "loom.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "loom.name" . }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 8000
      targetPort: http
