{{- if not .Values.oidc.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "loom.fullname" . }}-app
  labels:
    {{- include "loom.labels" . | nindent 4 }}
type: Opaque
stringData:
  oidc-client-secret: {{ .Values.oidc.clientSecret | quote }}
  session-secret: {{ .Values.app.sessionSecret | quote }}
{{- end }}
